###########################################################################################

# Stages to run
stages:
  queryMetadata: false
  queryFlags: false
  queryRandoms: false
  queryMaglimTomographic: true
  ingestData: false
  coverageMapper: false
  surveyPropertyMapper: false

###########################################################################################

global:
  # Name for pipeline run (outputs will be saved in a subdirectory with this name)
  run_name: tomo_maglim_i24p5
  # Conda environment name
  conda_env: patch3
  # Relevant directories
  paths:
    pipeline: /rds/general/user/tcornish/home/PATCH3/
    data: /rds/general/user/tcornish/ephemeral/Data/HSC_DR3/
    out: /rds/general/user/tcornish/home/PATCH3/outputs/
  # Data release
  dr: pdr3_wide
  # Fields to run (['all'] will be treated as ['hectomap', 'spring', 'autumn'])
  fields: [all]
  # Photometric bands
  bands:
    # Main band
    primary: i
    # List of all other bands
    secondary: [g, r, z, y]
    # Alternative names for some bands
    altnames:
      i: [i2]
      r: [r2]
  # Specify whether metadata should be split by band for queries and mapping
  split_by_band: true

### Data queries ###

queryBase: &queryBase
  runfile: data_queries.py
  username: tmcornish
  envsfile: patch3_envs.sh
  password_env: HSC_SSP_CAS_PASSWORD
  release: pdr3-citus-columnar

# Frame metadata
queryMetadata:
  <<: *queryBase
  sql_base: metadata
  qsub:
    walltime: 24:00:00
    resources:
      select: 1
      ncpus: 1
      mem: 100gb
  do_preview: false
  do_download: true
  do_delete: true

# Quality flags
queryFlags:
  <<: *queryBase
  sql_base: flags
  qsub:
    walltime: 24:00:00
    resources:
      select: 1
      ncpus: 1
      mem: 100gb
  do_preview: false
  do_download: true
  do_delete: true
  primary_only: true
  # Flags split by the catalogues to which they belong
  flags: &flags
    forced:
      pixelflags_edge: i
      pixelflags_interpolatedcenter: i
      pixelflags_saturatedcenter: i
      pixelflags_crcenter: i
      pixelflags_bad: i
      pixelflags_suspectcenter: i
      pixelflags_clipped: i
      cmodel_flag_badcentroid: i
    forced2:
      sdsscentroid_flag: i
    masks:
      mask_brightstar_ghost15: i
      mask_brightstar_halo: i
      mask_brightstar_blooming: i
      mask_brightstar_channel_stop: y
    meas:
      deblend_skipped: i

# Query from randoms catalogue
queryRandoms:
  <<: *queryBase
  sql_base: randoms
  qsub:
    walltime: 24:00:00
    resources:
      select: 1
      ncpus: 1
      mem: 100gb
  do_preview: false
  do_download: true
  do_delete: true
  primary_only: true
  density: 100  # per sq. arcmin (max 100)
  band_cols:
    pixelflags_edge: i
    pixelflags_interpolatedcenter: i
    pixelflags_saturatedcenter: i
    pixelflags_crcenter: i
    pixelflags_bad: i
    pixelflags_suspectcenter: i
    sky_std: grizy
  extra_cols: null

# Magnitude-limited tomographic samples
queryMaglimTomographic:
  <<: *queryBase
  sql_base: galaxies
  qsub:
    walltime: 24:00:00
    resources:
      select: 1
      ncpus: 1
      mem: 100gb
  samples:
    zbin0: [0.3, 0.6]
    zbin1: [0.6, 0.9]
    zbin2: [0.9, 1.2]
    zbin3: [1.2, 1.5]
  flags: 
    <<: *flags
  do_preview: false
  do_download: true
  do_delete: true
  primary_only: true
  log_blendedness_max: -0.375
  maglim: 24.5
  snr_min_primary: 10
  snr_min_secondary: 5
  N_sec: 2
  query_like_stars: true
  mag_type: cmodel
  correct_ri: true
  z_table: photoz_dnnz
  extra_cols:
    photoz_mizuki:
      - photoz_best
      - photoz_err68_min
      - photoz_err68_max
      - stellar_mass
      - stellar_mass_err68_min
      - stellar_mass_err68_max
      - sfr
      - sfr_err68_min
      - sfr_err68_max

### Data ingestion ###

ingestData:
  runfile: ingestion.py

### Mapping ###

coverageMapper:
  runfile: metadata_mapper.py
  qsub:
    walltime: 24:00:00
    resources:
      select: 1
      ncpus: 64
      mem: 920gb
  bands_to_run: grizy
  subdir: ''  # subdirectory of maps folder in which to store outputs
  decasu_params:
    nside: 16384

surveyPropertyMapper:
  runfile: metadata_mapper.py
  qsub:
    walltime: 24:00:00
    resources:
      select: 1
      ncpus: 64
      mem: 100gb
  bands_to_run: grizy
  subdir: ''  # subdirectory of maps folder in which to store outputs
  decasu_params:
    nside: 1024
    map_types:
      nexp: ['sum']
      exptime: ['sum']
      ccdtemp: ['mean']
      airmass: ['mean', 'min', 'max']
      seeing: ['mean']
      maglim: ['wmean']
      dcr_dra: ['mean']
      dcr_ddec: ['mean']
      dcr_e1: ['mean']
      dcr_e2: ['mean']
      sigma_sky: ['mean']
      skylevel: ['mean', 'mean-scaled']
      ellipticity: ['mean']
      weight: ['sum']
