--
-- put your SQL here
--
-- Run field, sql_files/run_COSMOS_DUD.sql
SELECT object_id,
	forced.ra as ra,
	forced.dec as dec,
	forced.tract as tract,
	forced.patch as patch,
	forced.merge_peak_g,
	forced.merge_peak_r,
	forced.merge_peak_i,
	forced.merge_peak_z,
	forced.merge_peak_y,
	forced.g_inputcount_value,
	forced.r_inputcount_value,
	forced.i_inputcount_value,
	forced.z_inputcount_value,
	forced.y_inputcount_value,
	forced.i_pixelflags_bright_objectcenter,
	forced.i_pixelflags_bright_object,
	forced.i_extendedness_value,
	meas2.i_blendedness_abs as i_blendedness_abs,
	forced.a_g,
	forced.a_r,
	forced.a_i,
	forced.a_z,
	forced.a_y,
	forced2.g_psfflux_flux,
	forced2.r_psfflux_flux,
	forced2.i_psfflux_flux,
	forced2.z_psfflux_flux,
	forced2.y_psfflux_flux,
	forced2.g_psfflux_fluxerr,
	forced2.r_psfflux_fluxerr,
	forced2.i_psfflux_fluxerr,
	forced2.z_psfflux_fluxerr,
	forced2.y_psfflux_fluxerr,
	forced2.g_psfflux_flag,
	forced2.r_psfflux_flag,
	forced2.i_psfflux_flag,
	forced2.z_psfflux_flag,
	forced2.y_psfflux_flag,
	forced2.g_psfflux_mag,
	forced2.r_psfflux_mag,
	forced2.i_psfflux_mag,
	forced2.z_psfflux_mag,
	forced2.y_psfflux_mag,
	forced2.g_psfflux_magerr,
	forced2.r_psfflux_magerr,
	forced2.i_psfflux_magerr,
	forced2.z_psfflux_magerr,
	forced2.y_psfflux_magerr,
	forced.g_cmodel_flux,
	forced.r_cmodel_flux,
	forced.i_cmodel_flux,
	forced.z_cmodel_flux,
	forced.y_cmodel_flux,
	forced.g_cmodel_fluxerr,
	forced.r_cmodel_fluxerr,
	forced.i_cmodel_fluxerr,
	forced.z_cmodel_fluxerr,
	forced.y_cmodel_fluxerr,
	forced.g_cmodel_flux,
	forced.r_cmodel_flux,
	forced.i_cmodel_flux,
	forced.z_cmodel_flux,
	forced.y_cmodel_flux,
	forced.g_cmodel_flag,
	forced.r_cmodel_flag,
	forced.i_cmodel_flag,
	forced.z_cmodel_flag,
	forced.y_cmodel_flag,
	forced.g_cmodel_mag,
	forced.r_cmodel_mag,
	forced.i_cmodel_mag,
	forced.z_cmodel_mag,
	forced.y_cmodel_mag,
	forced.g_cmodel_magerr,
	forced.r_cmodel_magerr,
	forced.i_cmodel_magerr,
	forced.z_cmodel_magerr,
	forced.y_cmodel_magerr,
	masks.g_mask_brightstar_ghost15,
	masks.r_mask_brightstar_ghost15,
	masks.i_mask_brightstar_ghost15,
	masks.z_mask_brightstar_ghost15,
	masks.y_mask_brightstar_ghost15,
	masks.g_mask_brightstar_halo,
	masks.r_mask_brightstar_halo,
	masks.i_mask_brightstar_halo,
	masks.z_mask_brightstar_halo,
	masks.y_mask_brightstar_halo,
	masks.g_mask_brightstar_blooming,
	masks.r_mask_brightstar_blooming,
	masks.i_mask_brightstar_blooming,
	masks.z_mask_brightstar_blooming,
	masks.y_mask_brightstar_blooming,
	masks.g_mask_brightstar_dip,
	masks.r_mask_brightstar_dip,
	masks.i_mask_brightstar_dip,
	masks.z_mask_brightstar_dip,
	masks.y_mask_brightstar_dip,
	forced.isprimary,
	forced.i_cmodel_flag_badcentroid,
	forced2.i_sdsscentroid_flag,
	forced.i_pixelflags_edge,
	forced.i_pixelflags_interpolatedcenter,
	forced.i_pixelflags_saturatedcenter,
	forced.i_pixelflags_crcenter,
	forced.i_pixelflags_bad,
	forced.i_pixelflags_suspectcenter,
	forced.i_pixelflags_clipped,
	meas.i_deblend_skipped,
	forced.isprimary,
	forced.i_cmodel_flag_badcentroid,
	meas.i_deblend_skipped,
	forced.g_cmodel_flag_badcentroid,
	forced.r_cmodel_flag_badcentroid,
	forced.i_cmodel_flag_badcentroid,
	forced.z_cmodel_flag_badcentroid,
	forced.y_cmodel_flag_badcentroid,
	forced2.g_sdsscentroid_flag,
	forced2.r_sdsscentroid_flag,
	forced2.i_sdsscentroid_flag,
	forced2.z_sdsscentroid_flag,
	forced2.y_sdsscentroid_flag,
	forced.g_pixelflags_edge,
	forced.r_pixelflags_edge,
	forced.i_pixelflags_edge,
	forced.z_pixelflags_edge,
	forced.y_pixelflags_edge,
	forced.g_pixelflags_interpolatedcenter,
	forced.r_pixelflags_interpolatedcenter,
	forced.i_pixelflags_interpolatedcenter,
	forced.z_pixelflags_interpolatedcenter,
	forced.y_pixelflags_interpolatedcenter,
	forced.g_pixelflags_saturatedcenter,
	forced.r_pixelflags_saturatedcenter,
	forced.i_pixelflags_saturatedcenter,
	forced.z_pixelflags_saturatedcenter,
	forced.y_pixelflags_saturatedcenter,
	forced.g_pixelflags_crcenter,
	forced.r_pixelflags_crcenter,
	forced.i_pixelflags_crcenter,
	forced.z_pixelflags_crcenter,
	forced.y_pixelflags_crcenter,
	forced.g_pixelflags_bad,
	forced.r_pixelflags_bad,
	forced.i_pixelflags_bad,
	forced.z_pixelflags_bad,
	forced.y_pixelflags_bad,
	forced.g_pixelflags_suspectcenter,
	forced.r_pixelflags_suspectcenter,
	forced.i_pixelflags_suspectcenter,
	forced.z_pixelflags_suspectcenter,
	forced.y_pixelflags_suspectcenter,
	forced.g_pixelflags_clipped,
	forced.r_pixelflags_clipped,
	forced.i_pixelflags_clipped,
	forced.z_pixelflags_clipped,
	forced.y_pixelflags_clipped,
	mag_corr.corr_rmag,
	mag_corr.corr_imag,
	pdemp.photoz_mean as pz_mean_demp,
	pdemp.photoz_mode as pz_mode_demp,
	pdemp.photoz_best as pz_best_demp,
	pdemp.photoz_mc as pz_mc_demp,
	pdemp.photoz_err68_min as pz_err68_min_demp,
	pdemp.photoz_err68_max as pz_err68_max_demp,
	pdemp.photoz_err95_min as pz_err95_min_demp,
	pdemp.photoz_err95_max as pz_err95_max_demp,
	pdnnz.photoz_mean as pz_mean_dnnz,
	pdnnz.photoz_mode as pz_mode_dnnz,
	pdnnz.photoz_best as pz_best_dnnz,
	pdnnz.photoz_mc as pz_mc_dnnz,
	pdnnz.photoz_err68_min as pz_err68_min_dnnz,
	pdnnz.photoz_err68_max as pz_err68_max_dnnz,
	pdnnz.photoz_err95_min as pz_err95_min_dnnz,
	pdnnz.photoz_err95_max as pz_err95_max_dnnz,
	pmizu.photoz_mean as pz_mean_mizu,
	pmizu.photoz_mode as pz_mode_mizu,
	pmizu.photoz_best as pz_best_mizu,
	pmizu.photoz_mc as pz_mc_mizu,
	pmizu.photoz_err68_min as pz_err68_min_mizu,
	pmizu.photoz_err68_max as pz_err68_max_mizu,
	pmizu.photoz_err95_min as pz_err95_min_mizu,
	pmizu.photoz_err95_max as pz_err95_max_mizu
FROM
	pdr3_dud.forced as forced
	LEFT JOIN pdr3_dud.forced2 USING (object_id)
	LEFT JOIN pdr3_dud.forced3 USING (object_id)
	LEFT JOIN pdr3_dud.mag_corr USING (object_id)
	LEFT JOIN pdr3_dud.meas meas USING (object_id)
	LEFT JOIN pdr3_dud.meas2 meas2 USING (object_id)
	LEFT JOIN pdr3_dud.masks masks USING (object_id)
	LEFT JOIN pdr3_dud.photoz_demp pdemp USING (object_id)
	LEFT JOIN pdr3_dud.photoz_dnnz pdnnz USING (object_id)
	LEFT JOIN pdr3_dud.photoz_mizuki pmizu USING (object_id)
WHERE
	forced.field='cosmos'
;